# Generated by Django 4.2 on 2026-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Paid', max_length=20),
        ),
    ]
