# Generated by Django 4.2 on 2026-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_image_remove_event_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Music', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(),
        ),
    ]
