# Generated by Django 4.2 on 2026-06-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_description_remove_event_total_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concerts & Live Music Performances', 'Concerts & Live Music Performances'), ('Corporate & Business Events', 'Corporate & Business Events'), ('Social & Private Events', 'Social & Private Events'), ('Community & Cultural Events', 'Community & Cultural Events'), ('Sports & Wellness', 'Sports & Wellness'), ('Educational & Workshop Events', 'Educational & Workshop Events')], default='Concerts & Live Music Performances', max_length=100),
        ),
    ]
